import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :crime_to_go, CrimeToGoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure offline debouncing (in milliseconds)
# Players going offline will only be logged if they stay offline for this duration
# Slightly higher in production to account for network latency
config :crime_to_go, offline_debounce_ms: 2000

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
